/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List users */
    get: operations['getUsers'];
    put?: never;
    /** Create user */
    post: operations['createUser'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/users/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    /** Get user detail */
    get: operations['getUserById'];
    put?: never;
    post?: never;
    /** Delete user */
    delete: operations['deleteUser'];
    options?: never;
    head?: never;
    /** Update user */
    patch: operations['updateUser'];
    trace?: never;
  };
  '/api/v1/complex/data': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Process complex data structure */
    post: operations['processComplexData'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ApiResponse: {
      /** @example 200 */
      code?: number;
      /** @example success */
      message?: string;
      data?: Record<string, never> | null;
    };
    PageResult: {
      page?: number;
      pageSize?: number;
      total?: number;
      items?: Record<string, never>[];
    };
    /**
     * @description User role enum
     * @enum {string}
     */
    UserRole: 'ADMIN' | 'USER' | 'GUEST';
    /**
     * @description 0: Inactive, 1: Active, 2: Suspended
     * @enum {integer}
     */
    UserStatus: 0 | 1 | 2;
    User: {
      /** Format: uuid */
      id: string;
      username: string;
      /** Format: email */
      email: string;
      role: components['schemas']['UserRole'];
      status?: components['schemas']['UserStatus'];
      tags?: string[];
      metadata?: {
        [key: string]: unknown;
      };
      /** Format: date-time */
      createdAt?: string;
    };
    CreateUserDto: {
      username: string;
      /** Format: password */
      password: string;
      /** Format: email */
      email?: string;
      /** @default USER */
      role: components['schemas']['UserRole'];
    };
    UpdateUserDto: {
      email?: string;
      status?: components['schemas']['UserStatus'];
    };
    ComplexObject: {
      nested?: {
        level2?: {
          key?: string;
        }[];
      };
      dynamicMap?: {
        [key: string]: components['schemas']['User'];
      };
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getUsers: {
    parameters: {
      query?: {
        page?: number;
        pageSize?: number;
        role?: components['schemas']['UserRole'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PageResult'] & {
            items?: components['schemas']['User'][];
          };
        };
      };
    };
  };
  createUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateUserDto'];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiResponse'] & {
            data?: components['schemas']['User'];
          };
        };
      };
    };
  };
  getUserById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiResponse'] & {
            data?: components['schemas']['User'];
          };
        };
      };
    };
  };
  deleteUser: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiResponse'];
        };
      };
    };
  };
  updateUser: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['UpdateUserDto'];
      };
    };
    responses: {
      /** @description Updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiResponse'];
        };
      };
    };
  };
  processComplexData: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['ComplexObject'];
      };
    };
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            result?: boolean;
            details?: {
              [key: string]: string;
            };
          };
        };
      };
    };
  };
}
