/**
 * 标准输出文件落地工具
 *
 * 将 StandardOutput 中的接口代码按 API 分类写入磁盘：
 * - 只被一个分类引用的接口写入该分类文件；
 * - 被多个分类（或无 API）引用的接口写入公共文件 `{modelsDir}/shared.ts`；
 * - 自动生成分检文件间的相对 import；
 * - 可选生成 barrel `index.ts`。
 */

import type { StandardOutput } from '@api-codegen-universal/core';

/** 输出选项 */
export interface EmitOptions {
  /** 输出根目录（不存在会自动创建） */
  outDir: string;
  /** 公共接口输出目录（相对 outDir）。默认 'models' */
  modelsDir?: string;
  /** 是否生成 barrel index.ts。默认 true */
  barrel?: boolean;
  /** 每个生成文件的头注释（默认标注生成工具名） */
  header?: string;
}

/** 输出结果 */
export interface EmitResult {
  /** 写入的文件路径（相对 outDir，POSIX 分隔符） */
  files: string[];
  /** 归入公共文件的接口名 */
  sharedNames: string[];
}

/** 共享接口文件名（相对 modelsDir） */
const SHARED_FILE = 'shared.ts';
/** barrel 文件名（相对 outDir） */
const BARREL_FILE = 'index.ts';

/** 生成文件固定头注释 */
const DEFAULT_HEADER =
  '/* eslint-disable */\n// Generated by api-codegen-universal. Do not edit by hand.';

/**
 * 将 StandardOutput 写入磁盘。
 *
 * @param output 适配器输出的标准格式
 * @param options 输出选项
 */
export async function emitStandardOutput(
  output: StandardOutput,
  options: EmitOptions,
): Promise<EmitResult> {
  const modelsDir = options.modelsDir ?? 'models';
  const barrel = options.barrel ?? true;
  const header = options.header ?? DEFAULT_HEADER;

  const interfaces = output.interfaces ?? {};
  const allNames = Object.keys(interfaces);
  const nameSet = new Set(allNames);

  // ---- 1. 构建 接口名 -> 直接引用的接口名集合 ----
  const references = new Map<string, Set<string>>();
  for (const name of allNames) {
    references.set(name, findReferencedNames(interfaces[name]!, nameSet));
  }

  // ---- 2. 收集每个 api 的直接引用（含响应头），解析泛型/数组包装 ----
  const directPerApi = output.apis.map((api) => {
    const refs = new Set<string>();
    const add = (ref: string | undefined): void => {
      if (!ref) return;
      for (const base of extractBaseNames(ref)) {
        if (nameSet.has(base)) refs.add(base);
      }
    };

    const params = api.parameters;
    if (params) {
      add(params.query?.ref);
      add(params.path?.ref);
      add(params.header?.ref);
      add(params.cookie?.ref);
    }
    if (api.requestBody) {
      for (const media of Object.values(api.requestBody.content)) {
        add(media.schema.ref);
      }
    }
    for (const response of Object.values(api.responses)) {
      if (response.content) {
        for (const media of Object.values(response.content)) {
          add(media.schema.ref);
        }
      }
      if (response.headers) {
        for (const headerDef of Object.values(response.headers)) {
          add(headerDef.schema.ref);
        }
      }
    }
    return refs;
  });

  // ---- 3. 闭包归属：接口名 -> 引用它的分类下标集合 ----
  const categoryOf = new Map<string, Set<number>>();
  directPerApi.forEach((direct, apiIndex) => {
    const visited = new Set<string>();
    const stack = [...direct];
    while (stack.length > 0) {
      const name = stack.pop()!;
      if (visited.has(name)) continue;
      visited.add(name);
      const cats = categoryOf.get(name) ?? new Set<number>();
      cats.add(apiIndex);
      categoryOf.set(name, cats);
      const refs = references.get(name);
      if (refs) {
        for (const ref of refs) {
          if (!visited.has(ref)) stack.push(ref);
        }
      }
    }
  });

  // ---- 4. 计算每个接口的目标文件 ----
  const sharedPath = posixJoin(modelsDir, SHARED_FILE);
  const targetFile = new Map<string, string>();
  const sharedNames: string[] = [];

  for (const name of allNames) {
    const cats = categoryOf.get(name);
    if (!cats || cats.size !== 1) {
      // 孤儿接口（无 api 引用）或多分类共享 → shared
      targetFile.set(name, sharedPath);
      sharedNames.push(name);
    } else {
      const api = output.apis[[...cats][0]!]!;
      targetFile.set(name, api.category.filePath);
    }
  }

  // ---- 5. 组装文件内容 ----
  /** fileRelPath -> { names: 接口名[], headerNote? } */
  const files = new Map<string, { names: string[]; note?: string }>();
  for (const name of allNames) {
    const file = targetFile.get(name)!;
    const entry = files.get(file) ?? { names: [] };
    entry.names.push(name);
    files.set(file, entry);
  }

  // 分类文件头注明包含的操作
  const operationsByCategory = new Map<string, string[]>();
  output.apis.forEach((api) => {
    const file = api.category.filePath;
    const list = operationsByCategory.get(file) ?? [];
    list.push(`${api.method} ${api.path} (${api.operationId})`);
    operationsByCategory.set(file, list);
  });

  const written: string[] = [];
  const posixOutDir = toPosix(options.outDir).replace(/\/+$/, '');

  for (const [file, entry] of files) {
    const lines: string[] = [header];

    if (entry.names.length === 0) continue;

    // 该文件文本中用到、但定义在别处的接口名 → 生成 import
    const ownNames = new Set(entry.names);
    const body = entry.names.map((name) => interfaces[name]!).join('\n\n');
    const imported = new Map<string, string[]>(); // importPath -> names
    for (const name of allNames) {
      if (ownNames.has(name)) continue;
      if (!hasWholeWord(body, name)) continue;
      const fromFile = targetFile.get(name)!;
      const importPath = relativeImport(file, fromFile);
      const list = imported.get(importPath) ?? [];
      list.push(name);
      imported.set(importPath, list);
    }

    if (imported.size > 0) {
      const sortedNames = (names: string[]) => [...names].sort();
      for (const [importPath, names] of imported) {
        lines.push(
          `import type { ${sortedNames(names).join(', ')} } from '${importPath}';`,
        );
      }
      lines.push('');
    }

    const operations = operationsByCategory.get(file);
    if (operations && operations.length > 0) {
      lines.push(`// Operations:`, ...operations.map((op) => `//   ${op}`), '');
    }

    lines.push(body, '');
    await writeFile(posixJoin(posixOutDir, file), lines.join('\n'));
    written.push(file);
  }

  // ---- 6. barrel ----
  if (barrel) {
    const exports = [...files.keys()]
      .sort()
      .filter((file) => file !== BARREL_FILE)
      .map((file) => `export * from '${relativeImport(BARREL_FILE, file)}';`);
    const barrelLines = [header, '', ...exports, ''];
    await writeFile(
      posixJoin(posixOutDir, BARREL_FILE),
      barrelLines.join('\n'),
    );
    written.push(BARREL_FILE);
  }

  return { files: written.sort(), sharedNames };
}

// ===================================================================================
// 辅助函数
// ===================================================================================

/** 解析 ref / 类型文本中的基础接口名：`A[]` → A，`Base<A, B[]>` → Base, A, B */
function extractBaseNames(ref: string): string[] {
  const names: string[] = [];
  // 把数组/泛型符号都替换为分隔符，逐层拆出全部基础名
  const cleaned = ref.replace(/[[\]<>]/g, ',');
  for (const part of cleaned.split(',')) {
    const name = part.trim();
    if (name) names.push(name);
  }
  return names;
}

/** 在代码文本中查找整词匹配的接口名 */
function hasWholeWord(text: string, name: string): boolean {
  const escaped = name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  return new RegExp(`\\b${escaped}\\b`).test(text);
}

/** 找到一段接口代码中引用的其他接口名 */
function findReferencedNames(code: string, nameSet: Set<string>): Set<string> {
  const found = new Set<string>();
  for (const name of nameSet) {
    // 跳过自身与" 定义名"（代码以 export ... <name> 开头）
    if (hasWholeWord(code, name)) {
      found.add(name);
    }
  }
  // 移除代码自身定义的名字
  const selfMatch = code.match(
    /export\s+(?:interface|type)\s+([A-Za-z0-9_$]+)/,
  );
  if (selfMatch && selfMatch[1]) found.delete(selfMatch[1]);
  return found;
}

/** POSIX 路径拼接 */
function posixJoin(...parts: string[]): string {
  return parts
    .map(toPosix)
    .filter((p) => p !== '')
    .join('/');
}

function toPosix(p: string): string {
  return p.replace(/\\/g, '/');
}

/**
 * 计算从 fromFile 到 toFile 的相对 import 路径（带 .js 后缀，ESM 友好）。
 * 两个参数都是相对 outDir 的 POSIX 路径。
 */
function relativeImport(fromFile: string, toFile: string): string {
  const fromParts = fromFile.split('/');
  fromParts.pop(); // 去掉文件名，留下目录
  const toParts = toFile.split('/');
  const fileName = toParts.pop()!.replace(/\.ts$/, '.js');

  let common = 0;
  while (
    common < fromParts.length &&
    common < toParts.length &&
    fromParts[common] === toParts[common]
  ) {
    common += 1;
  }
  const ups = fromParts.length - common;
  const downs = toParts.slice(common);
  const rel = [...Array.from({ length: ups }, () => '..'), ...downs];
  const joined =
    rel.length > 0 ? `${rel.join('/')}/${fileName}` : `./${fileName}`;
  // 同目录引用必须以 ./ 开头
  return joined.startsWith('.') ? joined : `./${joined}`;
}

async function writeFile(path: string, content: string): Promise<void> {
  const fs = await import('node:fs/promises');
  const nodePath = await import('node:path');
  await fs.mkdir(nodePath.dirname(path), { recursive: true });
  await fs.writeFile(path, content, 'utf-8');
}
